# Generated by Django 3.2.20 on 2023-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('semanas', models.IntegerField(default=0)),
                ('motivo', models.CharField(max_length=60)),
                ('triage', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
